### ISSUE TITLE
Not launching on Mojave

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [i3roly/firefox-dynasty#7] opened 2024-09-04 13:55 UTC
I've used this on multiple different systems with multiple different OS X/macOS versions, and while it works on most systems, on both Mojave systems I've tested on, it bounces for several minutes, then stops bouncing and goes to "application not responding". Chromium Legacy works fine.

**Comment by shakhbazian** [comment] 2024-10-14 16:47
Same behaviour on High Sierra, described in #11. Might be the same cause.

**Comment by Wowfunhappy** [comment] 2024-10-24 00:47
Can I suggest this be closed as a duplicate of #11? Unless/until we have reason to believe this is a separate problem for High Sierra vs Mojave, I think it makes more sense to track them together.

**Comment by kamisuna** [comment] 2024-10-25 07:42
This worked for Mojave
codesign --force --deep --sign - /Applications/Firefox.app

**Comment by i3roly** [comment] 2024-10-27 16:41
this should be fixed now too. @Wowfunhappy do you think you can close this if you agree?

**Comment by Wowfunhappy** [comment] 2024-10-27 16:42
I agree but can't close.

**Closed** 2024-10-27 16:43 UTC

**Comment by Wowfunhappy** [comment] 2024-10-30 14:04
Fwiw, some people on MacRumors seem to still be unable to start Firefox on Mojave. I don't (atm) have a Mojave VM to test with.

**Comment by i3roly** [comment] 2024-10-30 15:32
well, it's them, not the browser.

https://github.com/user-attachments/assets/8279dc6f-57ae-4c3c-be77-3d4ca3d17c2f

if they're using the version that works for you, anyways. they may assume it's the same file since the date on releases doesn't change (for some weird reason) when you update the file.
